version: 2.1
commands:
  firebase-deploy:
    description: Deploy to Firebase
    parameters:
      token:
        type: string
        description: Firebase Deploy Token
      alias:
        type: string
        default: "default"
        description: Firebase project alias to deploy to
    steps:
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=<< parameters.token >> -P << parameters.alias >>

jobs:
  build:
    docker:
      - image: "circleci/node:lts"
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: 'v1.1-yarn-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'v1.1-yarn-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: "circleci/node:lts"
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - firebase-deploy:
          token: $FIREBASE_DEPLOY_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
